'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ArrowUpRight,Search,Trash2,Plus} from 'lucide-react';
import {toast} from 'sonner';
import {safeUrl,siteSearchLink,type NewsSite} from '@/lib/news';
import {writeLibrary} from '@/lib/browser-library';
export default function SitesBar({sites,onChange,keywords,selected,onSelect,open,onOpenChange}:{sites:NewsSite[];onChange:(sites:NewsSite[])=>void;keywords:string;selected:string;onSelect:(url:string)=>void;open:boolean;onOpenChange:(open:boolean)=>void}){
 const [name,setName]=useState(''),[url,setUrl]=useState(''),[searchUrl,setSearchUrl]=useState('');
 function persist(next:NewsSite[]){writeLibrary({action:'sites',sites:next});onChange(next);}
 function submit(e:React.FormEvent){e.preventDefault();try{const normalized=safeUrl(url);const next=[...sites.filter(s=>s.url!==normalized),{name:name.trim()||new URL(normalized).hostname,url:normalized,searchUrl:searchUrl.trim()}];persist(next);setName('');setUrl('');setSearchUrl('');toast.success('Website added. Use its links or filter your stories.');}catch{toast.error('Enter a valid website URL. An optional search URL must use the same website and contain {query}. Maximum 30 sites.');}}
 return <><div className="sites-strip"><span className="eyebrow">YOUR SITES</span><button className={'site-scope '+(!selected?'active':'')} onClick={()=>onSelect('')}>All sites</button>{sites.map(site=><div className="site-entry" key={site.url}><button className={'site-scope '+(selected===site.url?'active':'')} title={'Show stories from '+new URL(site.url).hostname} onClick={()=>onSelect(selected===site.url?'':site.url)}>{site.name}</button><a href={site.url} target="_blank" rel="noopener noreferrer" title={'Open '+site.name} aria-label={'Open '+site.name}><ArrowUpRight size={15}/></a><a href={siteSearchLink(site,keywords)} target="_blank" rel="noopener noreferrer" title={'Search selected keywords on '+site.name} aria-label={'Search selected keywords on '+site.name}><Search size={14}/></a></div>)}{sites.length===0&&<span className="sites-hint">Add websites to search with your topic keywords.</span>}<button className="radar-edit" onClick={()=>onOpenChange(true)}><Plus size={15}/>Add / manage sites</button></div><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="editor"><DialogTitle>Add a website</DialogTitle><DialogDescription>Save a direct link and search the site with the keywords in your selected topic. “All stories” uses all your topics.</DialogDescription><form onSubmit={submit}><div className="site-form-row"><label>Website name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder="e.g. TechCrunch"/></label><label>Website URL<input value={url} onChange={e=>setUrl(e.target.value)} type="url" required maxLength={4096} placeholder="https://techcrunch.com"/></label></div><label>Site search URL (optional)<input value={searchUrl} onChange={e=>setSearchUrl(e.target.value)} maxLength={4096} placeholder="https://example.com/search?q={query}"/></label><p className="sites-help">Use {'{query}'} where the keywords go. Leave this blank to search this website through Google. “Show stories” uses the selected news sources and may not find every page.</p><button className="primary" disabled={sites.length>=30}>Add site</button></form>{sites.length>0&&<div className="saved-sites">{sites.map(site=><div key={site.url}><a href={site.url} target="_blank" rel="noopener noreferrer">{site.name}<small>{new URL(site.url).hostname}</small></a><button aria-label={'Remove '+site.name} onClick={()=>{try{persist(sites.filter(s=>s.url!==site.url));if(selected===site.url)onSelect('');}catch{toast.error('Could not save site changes.');}}}><Trash2 size={16}/></button></div>)}</div>}</DialogContent></Dialog></>;
}
