import assert from 'node:assert/strict';
import { parseFeed, safeUrl } from '../lib/news.ts';
const example = '<rss><item><title>A &amp; B</title><link>https://www.bing.com/news/apiclick.aspx?url=https%3A%2F%2Fexample.com%2Farticle</link><description>&lt;b&gt;Useful&lt;/b&gt; excerpt</description><News:Source>Example</News:Source></item><item><title>Bad</title><link>javascript:alert(1)</link></item></rss>';
const parsed = parseFeed(example, 'OpenAI');
assert.equal(parsed.length, 1);
assert.equal(parsed[0].url, 'https://example.com/article');
assert.equal(parsed[0].excerpt, 'Useful excerpt');
assert.equal(parsed[0].source, 'Example');
assert.throws(() => safeUrl('javascript:alert(1)'));
assert.throws(() => safeUrl('https://name:password@example.com'));
console.log('PASS: RSS parsing, original publisher links, and unsafe URL rejection.');
