import assert from 'node:assert/strict';
import {build} from 'esbuild';
const compiled=await build({entryPoints:['lib/news.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {siteSearchLink}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const url=siteSearchLink({name:'Example',url:'https://example.com',searchUrl:'https://example.com/search?q={query}'},'AI & governance');
assert.equal(new URL(url).searchParams.get('q'),'AI & governance');
const fallback=siteSearchLink({name:'Example',url:'https://example.com',searchUrl:''},'OpenAI OR AGI');
assert.equal(new URL(fallback).searchParams.get('q'),'site:example.com (OpenAI OR AGI)');
const encoded=siteSearchLink({name:'Example',url:'https://example.com',searchUrl:'https://example.com/s?q={query}'},'a b&c');
assert.equal(new URL(encoded).searchParams.get('q'),'a b&c','keywords are encoded, not injected');
console.log('PASS: native site searches, restricted fallback search, and keyword encoding.');
